### ISSUE TITLE
Display Tweaks

### ISSUE THREAD

**Issue by Doubletop12** [evilbunny2008/sensibo-python-sdk#3]
I had been changing my graph colours to something closer to what I saw as intuitive. Red for temperature, blue for humidity and green for feels like. I stopped doing it while updates were underway (No need for the hex codes the text works as well)

The icons you no doubt found in the box don't do justice to your efforts something a bit more subtle would be nicer.

Regarding the icons the on/off button confused me yesterday. Did red/off mean it was off or click it to switch off. Likewise for green/on? That is partly why I had my system on full for 2 hours before I noticed.  Maybe add ON or OFF to the current conditions line?

**Comment by evilbunny2008** [comment]
I'll add colour choices to mariadb.php, that should solve the first part.

As for on/off, it should display the current state, so on the aircon should be on, and vice versa.
